name: .NET Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'
      
      - name: Restore dependencies
        run: dotnet restore CalculatorApp.sln

      - name: Build
        run: dotnet build CalculatorApp.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test CalculatorApp.sln --configuration Release --no-build
        