name: Build and Test C# Solution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup .NET SDK (targeting .NET 7.0)
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Use stable .NET 7.0 SDK

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore CalculatorApp.sln

    # Step 4: Build the solution
    - name: Build the solution
      run: dotnet build CalculatorApp.sln --configuration Release --no-restore

    # Step 5: Run tests
    - name: Run tests
      run: dotnet test CalculatorApp.sln --no-build --verbosity normal