name: Build and Test C# Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Use the .NET version your project requires

    # Step 3: Restore dependencies for both src and tests
    - name: Restore dependencies for the main project
      run: dotnet restore src/CalculatorApp/CalculatorApp.csproj

    - name: Restore dependencies for the test project
      run: dotnet restore tests/CalculatorApp.Tests/CalculatorApp.Tests.csproj

    # Step 4: Build both projects
    - name: Build the main project
      run: dotnet build src/CalculatorApp/CalculatorApp.csproj --configuration Release --no-restore

    - name: Build the test project
      run: dotnet build tests/CalculatorApp.Tests/CalculatorApp.Tests.csproj --configuration Release --no-restore

    # Step 5: Run tests
    - name: Run tests
      run: dotnet test tests/CalculatorApp.Tests/CalculatorApp.Tests.csproj --no-build --verbosity normal